name: Keep APIs Alive

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:        # Allows manual triggering too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call API 1
        run: curl https://payment-c98i.onrender.com/api/user/ping
      - name: Call API 2
        run: curl https://userdetailmicroservice.onrender.com/api/userdetails/ping
      - name: Call API 3
        run: curl https://imagemicroservice.onrender.com/api/images/ping
      - name: Call API 4
        run: curl https://authmicroservice-w2pn.onrender.com/api/auth/ping
